from hackathon.models import Hackathon
from developer.models import Developer

def migrate_db():
    h1 = Hackathon.objects.create(title='Hackathon 1')
    h2 = Hackathon.objects.create(title='Hackathon 2')
    h3 = Hackathon.objects.create(title='Hackathon 3')

    Developer.objects.create(first_name='name 1', last_name='surname 1', position=10, hackathon=h1)
    Developer.objects.create(first_name='name 2', last_name='surname 2', position=9, hackathon=h1)
    Developer.objects.create(first_name='name 3', last_name='surname 3', position=8, hackathon=h1)
    Developer.objects.create(first_name='name 4', last_name='surname 4', position=1, hackathon=h1)
    Developer.objects.create(first_name='name 5', last_name='surname 5', position=7, hackathon=h1)
    Developer.objects.create(first_name='name 6', last_name='surname 6', position=6, hackathon=h1)
    Developer.objects.create(first_name='name 7', last_name='surname 7', position=12, hackathon=h1)
    Developer.objects.create(first_name='name 8', last_name='surname 8', position=2, hackathon=h1)
    Developer.objects.create(first_name='name 9', last_name='surname 9', position=3, hackathon=h1)
    Developer.objects.create(first_name='name 10', last_name='surname 10', position=11, hackathon=h1)
    Developer.objects.create(first_name='name 11', last_name='surname 11', position=5, hackathon=h1)
    Developer.objects.create(first_name='name 12', last_name='surname 12', position=4, hackathon=h1)

    Developer.objects.create(first_name='name 1', last_name='surname 1', position=8, hackathon=h3)
    Developer.objects.create(first_name='name 2', last_name='surname 2', position=12, hackathon=h3)
    Developer.objects.create(first_name='name 3', last_name='surname 3', position=5, hackathon=h3)
    Developer.objects.create(first_name='name 4', last_name='surname 4', position=4, hackathon=h3)
    Developer.objects.create(first_name='name 5', last_name='surname 5', position=3, hackathon=h3)
    Developer.objects.create(first_name='name 6', last_name='surname 6', position=2, hackathon=h3)
    Developer.objects.create(first_name='name 7', last_name='surname 7', position=1, hackathon=h3)
    Developer.objects.create(first_name='name 8', last_name='surname 8', position=7, hackathon=h3)
    Developer.objects.create(first_name='name 9', last_name='surname 9', position=6, hackathon=h3)
    Developer.objects.create(first_name='name 10', last_name='surname 10', position=10, hackathon=h3)
    Developer.objects.create(first_name='name 11', last_name='surname 11', position=9, hackathon=h3)
    Developer.objects.create(first_name='name 12', last_name='surname 12', position=11, hackathon=h3)

    Developer.objects.create(first_name='name 1', last_name='surname 1', position=3, hackathon=h2)
    Developer.objects.create(first_name='name 2', last_name='surname 2', position=1, hackathon=h2)
    Developer.objects.create(first_name='name 3', last_name='surname 3', position=11, hackathon=h2)
    Developer.objects.create(first_name='name 4', last_name='surname 4', position=4, hackathon=h2)
    Developer.objects.create(first_name='name 5', last_name='surname 5', position=2, hackathon=h2)
    Developer.objects.create(first_name='name 6', last_name='surname 6', position=6, hackathon=h2)
    Developer.objects.create(first_name='name 7', last_name='surname 7', position=5, hackathon=h2)
    Developer.objects.create(first_name='name 8', last_name='surname 8', position=12, hackathon=h2)
    Developer.objects.create(first_name='name 9', last_name='surname 9', position=10, hackathon=h2)
    Developer.objects.create(first_name='name 10', last_name='surname 10', position=7, hackathon=h2)
    Developer.objects.create(first_name='name 11', last_name='surname 11', position=9, hackathon=h2)
    Developer.objects.create(first_name='name 12', last_name='surname 12', position=8, hackathon=h2)
